routes/web.php
<?php

Route::get('/test',function(){
    $runs = [];
    $prev = 0;
    for($i = 0; $i<date('z');$i++){
        $date = date('Y-m-d',strtotime('1st January 2018 + ' . $i . ' days'));
        $distance = \App\Run::whereDate('start_date',$date)->get()->sum('distance')/1000 ?? 0;
        $distance += $prev;
        $runs[$date] = $distance;
        $prev = $distance;
    }
    $points = \Illuminate\Support\Facades\Cache::get('points');
    $points_count = count($points);
    foreach($runs as $date => $distance) {
        $current_distance = $distance;
        $calculated_distance = 0;
        $count = 1;
        $last_point = $points[0];
        for ($i = 1; $i < $points_count; $i++) {
            if ($calculated_distance < $current_distance) {
                $count++;
                $current_point = $points[$i];
                $distance = distance($last_point[0], $last_point[1], $current_point[0], $current_point[1], 'km', 10);
                if (!is_nan($distance)) {
                    $calculated_distance += $distance;
                    $last_point = $current_point;
                }

            }

        }
        $runs[$date] = getTown(implode(',',$points[$count]));
    }
    dd($runs);


});

Route::get('/',function(){

    $points = \Illuminate\Support\Facades\Cache::get('points');
    $points_count = count($points);
    $current_distance = distanceRan();
    $calculated_distance = 0;
    $count = 1;
    $last_point = $points[0];
    for($i=1;$i<$points_count;$i++){
        if($calculated_distance<$current_distance) {
            $count++;
            $current_point = $points[$i];
            $distance = distance($last_point[0], $last_point[1], $current_point[0], $current_point[1],'km',10);
            if(!is_nan($distance)){
                $calculated_distance += $distance;
                $last_point = $current_point;
            }

        }

    }
    $done_points = $points->take($count);
    $current_point = $points->slice($count-1,1)->first();
    $todo_points = $points->slice($count-1,10000);
    $todo_points2 = $points->slice($count-1+10000,$points_count-$count-10000);
    $i = 0;
    $result = [];
    foreach ($todo_points2 as $point){
        if ($i++ % 5 == 0) {
            $result[] = $point;
        }
    }
    $todo_points2 = collect($result);

    $todo_points = $todo_points->merge($todo_points2);
    $last_sunday = date('Y-m-d',strtotime('last sunday'));
    $last_monday = date('Y-m-d',strtotime($last_sunday . ' - 6 days'));
    $last_week_runs = round(\App\Run::whereDate('start_date','>=',$last_monday)->whereDate('start_date','<=',$last_sunday)->sum('distance')/1000,3);
    $yesterday_distance = round(App\Run::whereDate('start_date',date('Y-m-d',strtotime('yesterday')))->sum('distance')/1000,3);
    return view('homepage')->with([
        'todays' => \App\Run::with('athlete')->whereDate('start_date',date('Y-m-d',strtotime('today')))->get()->sortByDesc('start_date'),
        'yesterday_distance' => $yesterday_distance,
        'last_week_distance' => $last_week_runs,
        'runs' => \App\Run::with('athlete')->get()->groupBy(function($item){
            return date('Y-m',strtotime($item->start_date));
        })->sortByDesc(function($item,$key){
            return $key;
        }),
        'athletes' => \App\Athlete::all(),
        'points' => [$done_points,$todo_points,$current_point],
        'current_town' => getTown(implode(',',$points[$count])),
    ]);

});

Route::get('/manual',function(){
    return view('manual');
});

Route::post('/manual',function(\Illuminate\Http\Request $request){
    if($request->password == env('ADMIN_PASS')) {
        $run = new \App\Run();
        $run->external_id = "manual_" . time();
        $run->athlete_id = $request->athlete;
        $run->name = $request->title;
        $run->distance = floatval($request->distance * 1000);
        $run->start_date = date('Y-m-d H:i:s', strtotime($request->start_time));
        $run->save();
    }
    return redirect('/');
});

Route::post('/manual_remove',function(\Illuminate\Http\Request $request){
    if($request->password == env('ADMIN_PASS')) {
        \App\Run::find($request->run)->delete();
    }
    return redirect('/');
});

app/Athlete.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Athlete extends Model
{
    public function runs()
    {
        return $this->hasMany('App\Run');
    }

    public function getFormattedNameAttribute()
    {
        return ucwords($this->name . ' ' . $this->surname);
    }

    public function getTotalDistanceAttribute(){
        return round($this->runs()->sum('distance')/1000,3);
    }

    public function getProjectedDistanceAttribute(){
        $divide = (date('W')-1) + 52;
        if($divide < 1){
            $divide = 1;
        }
        $calculation = ((($this->total_distance/$divide)*52)/365)*(howManyDaysToGoal()+365);
        return round($calculation,3);
    }

    public function getWeeklyTargetAttribute(){
        $ability = ($this->total_distance / distanceRan());
        $distance = distanceToGoal() * $ability;
        $distancePerDay = $distance / howManyDaysToGoal();
        $distancePerWeek = $distancePerDay * 7;
        return round($distancePerWeek,3);
    }

    public function getWeeklyDistanceAttribute(){
        return round($this->runs->filter(function($run){
            return ((date('W')) == date('W',strtotime($run->start_date)) && date('Y',strtotime($run->start_date)) == '2019');
        })->sum('distance_km'),3);
    }

    public function getLeftWeeklyAttribute(){
        return $this->weekly_target-$this->weekly_distance;
    }

    public function getProfileAttribute(){
        $profile = $this->attributes['profile'];
        if(starts_with($profile,'http')){
            return $profile;
        }

        return "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png";
    }
}

app/Run.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Run extends Model
{
    public function athlete(){
        return $this->belongsTo('App\Athlete');
    }

    public function getDistanceKmAttribute(){
        return $this->distance / 1000;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/homepage.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>EdRob Running</title>
    <link href="/css/app.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <style>
        .clock{


            font-family: 'Inconsolata', monospace;
            font-size: 44px;


        }
        body{
            padding-top:40px;
        }
        #map {
            height: 500px;
            max-width: 100%;
        }
        .panel-body{
            display:flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            min-height:120px;
        }
        .panel-title{
            text-align: center;
        }
        .panel-flex{
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-direction: row;
            min-height: 50px;
            width:100%;
        }
        .panel-flex h4{
            width:100%;
        }
    </style>
</head>
<body>
<div class="container">
</div>
<div class="container">
    <div class="row">
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Total Distance</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">{{env('TOTAL_DISTANCE')}}</strong>km</span>
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">We have run</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">{{distanceRan()}}</strong>km</span>
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Still to go</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">{{distanceToGoal()}}</strong>km</span>
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Average per day</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">{{distanceAverage()}}</strong>km</span>
                    <div><small style="text-align: center">We will reach destination on <strong>{{ whatDateWeWillReachGoal() }}</strong> ({{howManyDaysToGoal()}} days)</small></div>
                </div>
            </div>
        </div>

        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">We are in or near</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock" style="font-size: 24px;">{{$current_town}}</strong></span>


                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Overall Progress</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock" style="font-size: 24px;">{{distancePercentage2()}}</strong>%</span>
                    <div class="progress" style="width: 100%">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{distancePercentage()}}" aria-valuemin="0" aria-valuemax="100" style="width: {{distancePercentage()}}%;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Last week we ran</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">{{distanceLastWeek()}}</strong>km</span>
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">&nbsp;</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">    <a href='http://www.justgiving.com/edrob-runners' title='JustGiving - Sponsor me now!' target='_blank'><img src='http://www.justgiving.com/App_Themes/JustGiving/images/badges/badge10.gif' width='270' height='50' alt='JustGiving - Sponsor me now!' /></a>
</strong></span>
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Yesterday we ran</h3>
                </div>
                <div class="panel-body">
                    <span><strong class="clock">{{$yesterday_distance}}</strong>km</span>
                </div>
            </div>
        </div>
    </div>


</div>
<div class="container">
    <h2 style="text-align: center;">Today's Runs</h2>

    <div class="row">
        <div class="column col-md-12">
            @if($todays->count() > 0)
                <h4 style="text-align: center;">Total Today: <strong>{{round($todays->sum('distance')/1000,1)}}km</strong> {!! howMuchMoreWeNeedToday($todays) !!}</h4>
                {!! todaysPercentage($todays) !!}
                <table class="table table-striped table-condensed" >
                    <tr>
                        <th>Name</th>
                        <th>Distance</th>
                        <th>Date and Time</th>
                    </tr>
                    @foreach($todays as $run)
                        <tr>
                            <td style="vertical-align: middle;"><img src="{{$run->athlete->profile}}" style="max-width:32px;border-radius: 4px;"/>  {{ $run->athlete->formatted_name }}</td>
                            <td style="vertical-align: middle;">{{ $run->distance_km }}km</td>
                            <td style="vertical-align: middle;">{{date('d/m/Y H:i:s',strtotime($run->start_date))}}</td>
                        </tr>
                    @endforeach
                </table>
            @else
                <div class="alert alert-warning" style="text-align: center">No runs today :(<br/>Today's Target is <strong>{{howMuchWeNeedPerDay()}}km</strong>. That's only <strong>{{ round(howMuchWeNeedPerDay()/\App\Athlete::count(),2) }}km</strong> per person!</div>
            @endif
        </div>
    </div>
</div>
<div class="container" style="min-height: 500px;margin-bottom:20px;">
    <div id="map" style="border-radius: 4px;"></div>
    <script>

        // This example creates a 2-pixel-wide red polyline showing the path of
        // the first trans-Pacific flight between Oakland, CA, and Brisbane,
        // Australia which was made by Charles Kingsford Smith.

        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 9,
                center: {lat: {{$points[2][0]}}, lng: {{$points[2][1]}} },
                mapTypeId: 'terrain'
            });

            var currentPath = [
                @foreach($points[0] as $point)
                { lat: {{$point[0]}}, lng: {{$point[1]}} },
                @endforeach
            ];
            var planedPath = [
                @foreach($points[1] as $point)
                { lat: {{$point[0]}}, lng: {{$point[1]}} },
                @endforeach
            ];
            var aPath = new google.maps.Polyline({
                path: planedPath,
                geodesic: true,
                strokeColor: '#FF0000',
                strokeOpacity: 1.0,
                strokeWeight: 5
            });

            var bPath = new google.maps.Polyline({
                path: currentPath,
                geodesic: true,
                strokeColor: '#00FF00',
                strokeOpacity: 1.0,
                strokeWeight: 10
            });

            aPath.setMap(map);
            bPath.setMap(map);
        }
    </script>

</div>

    <div class="container">
        @include('users')
        @foreach($runs as $month => $data)
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="panel-flex"><h4>
                                <table class="table">
                                    <tr>
                                        <th style="border-top: 0px solid black; width:20%;"></th>
                                        <th class="hidden-xs" style="border-top: 0px solid black; width:20%;">Distance</th>
                                        <th class="hidden-xs" style="border-top: 0px solid black; width:20%;">Difference</th>
                                        <th class="hidden-xs" style="border-top: 0px solid black; width:20%;">Average</th>
                                        <th class="hidden-xs" style="border-top: 0px solid black; width:20%;"></th>
                                    </tr>
                                    <tr>
                                        <td style="border-top: 0px solid black; width:20%;">{{date('F Y',strtotime($month))}}</td>
                                        <td class="hidden-xs" style="border-top: 0px solid black;width:20%;">{{round($data->sum('distance')/1000,1)}}km</td>
                                        <td class="hidden-xs" style="border-top: 0px solid black;width:20%;">{!!( ((round($data->sum('distance')/1000 - env('TOTAL_DISTANCE')/12,1)) > 0)?'<span class="label label-success">+'.(round($data->sum('distance')/1000 - env('TOTAL_DISTANCE')/12,1)).'km</span>' : '<span class="label label-danger">'.(round($data->sum('distance')/1000 - env('TOTAL_DISTANCE')/12,1)).'km</span>')!!}</td>
                                        <td class="hidden-xs" style="border-top: 0px solid black;width:20%;">{{round(($data->sum('distance')/1000)/daysInAMonth($month),1)}}km</td>
                                        <td style="border-top: 0px solid black;width:20%;"><button class="btn btn-primary pull-right" type="button" data-toggle="collapse" data-target="#{{$month}}" aria-expanded="false" aria-controls="{{$month}}">Toggle</button></td>
                                    </tr>
                                </table>
                                 </h4></div>
                        <div class="collapse" id="{{$month}}" style="width: 100%;">
                            <div class="well">
                                <table class="table table-striped table-condensed" >
                                    <tr>
                                        <th>Name</th>
                                        <th>Distance</th>
                                        <th>Date and Time</th>
                                    </tr>
                                    @foreach($data->sortByDesc('start_date') as $run)
                                        <tr>
                                            <td style="vertical-align: middle;"><img src="{{$run->athlete->profile}}" style="max-width:32px;border-radius: 4px;"/>&nbsp;&nbsp;&nbsp;{{ $run->athlete->formatted_name }}</td>
                                            <td style="vertical-align: middle;">{{ $run->distance_km }}km</td>
                                            <td style="vertical-align: middle;">{{date('d/m/Y H:i:s',strtotime($run->start_date))}}</td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

        @endforeach

    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{env('GOOGLE_API')}}&callback=initMap"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<p style="width:100%;padding:20px 0;text-align: center;">Developed by David Zborowski {{date('Y')}}</p>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
</body>
</html>

resources/views/manual.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>EdRob Running</title>
    <link href="/css/app.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <style>
        .clock{


            font-family: 'Inconsolata', monospace;
            font-size: 44px;


        }
        body{
            padding-top:40px;
        }
        #map {
            height: 500px;
            max-width: 100%;
        }
        .panel-body{
            display:flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            min-height:120px;
        }
        .panel-title{
            text-align: center;
        }
        .panel-flex{
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-direction: row;
            min-height: 50px;
            width:100%;
        }
        .panel-flex h4{
            width:100%;
        }
    </style>
</head>
<body>
<div class="container">
    <form action="/manual" method="post">
        {{csrf_field()}}
        <div class="form-group">
            <label for="exampleInputFile">Title</label>
            <input type="text" name="title" class="form-control" id="exampleInputPassword1" placeholder="Title">
        </div>
        <div class="form-group">
            <label for="exampleInputFile">Athlete</label>
            <select name="athlete" class="form-control">
                @foreach(\App\Athlete::all() as $athlete)
                    <option value="{{$athlete->id}}">{{$athlete->formatted_name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Distance (in KM)</label>
            <input type="number" name="distance" step="0.001" min="0.001" class="form-control" id="exampleInputEmail1" placeholder="0.001">
        </div>

        <div class="form-group">
            <label for="exampleInputFile">Run Start Date & Time</label>
            <input type="datetime-local" name="start_time" class="form-control" id="exampleInputPassword1" value="{{date('Y-m-d\TH:i:s')}}">
        </div>
        <div class="form-group">
            <label for="exampleInputFile">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>

        <button type="submit" class="btn btn-success">Add</button>
    </form>

    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>

    <form action="/manual_remove" method="post">
        {{csrf_field()}}
        <div class="form-group">
            <label for="exampleInputFile">Run</label>
            <select name="run" class="form-control">
                @foreach(\App\Run::take(10)->orderByDesc('start_date')->get() as $run)
                    <option value="{{$run->id}}">{{$run->athlete->formatted_name . " [" . $run->distance . "m] @ " . $run->start_date}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="exampleInputFile">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>

        <button type="submit" class="btn btn-danger">Remove</button>
    </form>
</div>
</body>
</html>

resources/views/users.blade.php
<div class="row" style="margin-bottom: 40px;">
    @foreach($athletes->sortBy(function($item){
        return ucwords($item->surname);
    }) as $user)
        <div class="column col-md-4" style="min-height: 185px;">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <div class="media-object" style="position:relative;width: 150px;height: 150px;border-radius: 4px; background: url({{$user->profile}}); background-size: cover;">
                            @if($user->left_weekly<0)
                            <img src="/medal.png" style="width:70px;position:relative;top:6px;"/>
                            @endif
                        </div>
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{$user->formatted_name}}</h4>
                    <h3 style="margin:5px 0;">{{$user->total_distance}}km</h3>
                    <small style="margin:0;" data-toggle="tooltip" data-placement="left" title="@ Current Rate">Projection: {{$user->projected_distance}}km</small>
                    <p style="margin:0;" data-toggle="tooltip" data-placement="left" title="Weekly Target"><small>Weekly Target: </small>{{$user->weekly_target}}km</p>
                    <p style="margin:0;" data-toggle="tooltip" data-placement="left" title="Done This Week"><small>Done This Week: </small>{{$user->weekly_distance}}km</p>
                    <p style="margin:0;" data-toggle="tooltip" data-placement="left" title="{{($user->left_weekly<0?'Bonus':'Left')}} This Week"><small>{{($user->left_weekly<0?'Bonus':'Left')}} This Week: </small>{{($user->left_weekly<0?$user->left_weekly*-1:$user->left_weekly)}}km</p>

                </div>
                <div class="progress" style="width: 100%; margin: 5px 0;">
                    <div class="progress-bar {{(round(($user->weekly_distance/$user->weekly_target)*100,0) == 0? 'progress-bar-danger' :'progress-bar-success')}}" role="progressbar" aria-valuenow="{{round(($user->weekly_distance/$user->weekly_target)*100,0)}}" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: {{(round(($user->weekly_distance/$user->weekly_target)*100,0) > 100 ? 100 :round(($user->weekly_distance/$user->weekly_target)*100,0)) }}%;">
                        {{round(($user->weekly_distance/$user->weekly_target)*100,0)}}%
                    </div>
                </div>
            </div>
        </div>
    @endforeach
</div>